### ISSUE TITLE
Chatroom history as context

### ISSUE THREAD

**Issue by torrybr** [etkecc/baibot#24] opened 2024-12-09 22:18 UTC
Can a chatroom's history be used as context for bot responses? I found this context management section: 
https://github.com/etkecc/baibot/blob/main/docs/configuration/text-generation.md#%EF%B8%8F-context-management. What are the limits? Can thousands of messages be included as context?

**Comment by spantaleev** [comment] 2024-12-10 08:34
Duplicate of https://github.com/etkecc/baibot/issues/20

**Closed by spantaleev** 2024-12-10 08:34 UTC
